apiVersion: apps/v1
kind: Deployment
metadata:
  name: heliocentric-model-no-pluto
spec:
  selector:
    matchLabels:
      app: heliocentric-model-no-pluto
  replicas: 2
  template:
    metadata:
      labels:
        app: heliocentric-model-no-pluto
    spec:
      containers:
      - name: heliocentric-model-no-pluto
        image: siddharth67/heliocentric-solar-system:no-pluto
