apiVersion: v1
kind: Service
metadata:
  name: heliocentric-model-no-pluto-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: heliocentric-model-no-pluto
  type: NodePort
